spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sample
    username: lakshman
    password: lakshman@123
    hikari:
      maximum-pool-size: 8
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 8090
  servlet:
    context-path: /todo